name: .NET Core build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    services:
      redis:
        image: 'redis:6.0.5'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 50605:6379

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Rediska/Rediska.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        TAG_COMMIT: true
        TAG_FORMAT: v*
        NUGET_KEY: ${{secrets.NUGETKEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true
